name: ABL IT Business IT Specialists
favicon: null
layout_spectrum: 1
typography_spectrum: 0.47935949987731874
title: ABL IT - Business IT Specialists
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#231f20'
    - '#f16321'
    - '#f9cab1'
    - '#909090'
  brandStrength: 0.9449826416093856
  lightness: 0.06369226286187768
  saturation: 0.5940267227124423
  rhythmicContrast: 0.28211930487304926
purpose: []
